# Site settings
title: Walter Nadalin
description: Resumé
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Walter Nadalin
user_description: I am a student, always ready to learn and improve, taking on new challenges and traveling towards new horizons. Lately I have been immersing myself in the world of distributed quantum computing, working as an intern on quantum algorithms with Welinq, a Paris based startup that seeks to provide solutions for the interconnection of quantum processes. 
user_title: Student
email: walternadalin4@gmail.com
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
#linkedin_username: murraco
github_username:  WalterNadalin
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

